#!/usr/bin/env python

# My Awesome Module main

from __future__ import print_function
import sys
from my_module import metadata

def main(argv=None):
    if argv is None:
        argv = sys.argv
    print(metadata.nice_title, metadata.version, end='\n\n')
    print(metadata.description, end='\n\n')
    for name, email in zip(metadata.authors, metadata.emails):
        print('Author: {0} <{1}>'.format(name, email))
    print('URL:', metadata.url)

if __name__ == '__main__':
    sys.exit(main())
